[rest_countries]
url = "https://api.restcountries.com/countries/v5"
response_fields = "names.common,official,capitals.name,region,subregion,area,calling_codes,currencies,government_type,population,timezones"
limit = 100
filename = "countries_raw_filtered.json"

[logging]
level = "INFO"

[database]
port = 5432

[database.raw]
schema = "raw_countries"
table = "countries_raw"

[database.transformed]
schema = "analytics"
table = "countries"

[database.currencies]
schema = "analytics"
table = "country_currencies"